#' Run KEGG interactive editor and visualization App
#' 
#' @param port The TCP port that the application should listen on. Default value is 3838
#' 
#' @return Nothing is returned
#' 
#' @examples
#' \dontrun{
#'     runShinyApp()
#' }
#' 
#' @concept psf
#' @export
run_shiny_app <- function(port=3838) {
  shiny::runApp(system.file('shinyApp', package='psf'), port=port, launch.browser = TRUE)	
}

### need to work on this
#' Run KEGG interactive visualization App for provided pathway
#' 
#' @param pathway list object
#' @param port The TCP port that the application should listen on. Default value is 3838
#' 
#' @return Nothing is returned
#' 
#' @examples
#' \dontrun{
#'     runShinyApp()
#' }
#' 
#' @concept psf
#' @export
pathway_shiny_vis <- function(pathway, port = 3838) {
  shiny::runApp(system.file('vis_app', package='psf'), port=port, launch.browser = TRUE)	
}



#' Run spatial PSF browser App
#' 
#' @param psf_saptial_results list object generated by spatial_psf_analysis function.
#' @param port The TCP port that the application should listen on. Default value is 3838
#' 
#' @return Nothing is returned
#' 
#' @examples
#' \dontrun{
#'     runShinyApp()
#' }
#' 
#' @concept psf
#' @import shiny
#' @export
run_psf_spatial_browser <- function(psf_spatial_results, port = 3838) {
  
  if (!requireNamespace("Seurat", quietly = TRUE)) {
    stop("This function requires the 'Seurat'. Please install it using install.packages('Seurat').")
  }
  
  shinyOptions(psf_spatial_results = psf_spatial_results)
  
  shiny::runApp(system.file('spatial_browser', package='psf'), port=port, launch.browser = TRUE)	
}
