name: pkgdown

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libcurl4-openssl-dev libxml2-dev libssl-dev libmagick++-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("remotes","pkgdown","roxygen2"), repos="https://cloud.r-project.org")'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'

      - name: Build site
        run: |
          Rscript -e 'pkgdown::build_site(new_process = FALSE)'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs